development:
  adapter: postgresql
  database: mycosts_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: mycosts_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mycosts_production
  pool: 5
  timeout: 5000
